Repository cloudforet-io/inventory-v2, pull requests merged in 2024-12, with the labels that each got.

#6 Add collector plugin connector for v1 and v2
  src/spaceone/inventory_v2/conf/collector_conf.py
  src/spaceone/inventory_v2/connector/__init__.py
  src/spaceone/inventory_v2/connector/collector_plugin_connector/__init__.py
  src/spaceone/inventory_v2/connector/collector_plugin_connector/collector_plugin_v1_connector.py
  src/spaceone/inventory_v2/connector/collector_plugin_connector/collector_plugin_v2_connector.py
  src/spaceone/inventory_v2/error/__init__.py
  src/spaceone/inventory_v2/error/metric.py
  src/spaceone/inventory_v2/interface/grpc/metric.py
  src/spaceone/inventory_v2/manager/__init__.py
  src/spaceone/inventory_v2/manager/asset_manager.py
  src/spaceone/inventory_v2/manager/asset_type_manager.py
  src/spaceone/inventory_v2/manager/cleanup_manager.py
  src/spaceone/inventory_v2/manager/collecting_manager.py
  src/spaceone/inventory_v2/manager/collection_state_manager.py
  src/spaceone/inventory_v2/manager/collector_plugin_manager.py
  src/spaceone/inventory_v2/manager/job_manager.py
  src/spaceone/inventory_v2/manager/job_task_manager.py
  src/spaceone/inventory_v2/manager/managed_resource_manager.py
  src/spaceone/inventory_v2/manager/metric_data_manager.py
  src/spaceone/inventory_v2/manager/metric_manager.py
  src/spaceone/inventory_v2/model/__init__.py
  src/spaceone/inventory_v2/model/asset/database.py
  src/spaceone/inventory_v2/model/asset/request.py
  src/spaceone/inventory_v2/model/asset/response.py
  src/spaceone/inventory_v2/model/asset_type/database.py
  src/spaceone/inventory_v2/model/asset_type/request.py
  src/spaceone/inventory_v2/model/asset_type/response.py
  src/spaceone/inventory_v2/model/collector/database.py
  src/spaceone/inventory_v2/model/collector/response.py
  src/spaceone/inventory_v2/model/metric/request.py
  src/spaceone/inventory_v2/service/__init__.py
  src/spaceone/inventory_v2/service/asset_service.py
  src/spaceone/inventory_v2/service/asset_type_service.py
  src/spaceone/inventory_v2/service/collector_service.py
Labels: enhancement

#7 Modify inventory-v2 collector response spec
  src/spaceone/inventory_v2/conf/global_conf.py
  src/spaceone/inventory_v2/model/collector/response.py
Labels: bug

#8 Modify inventory-v2 collector request spec
  src/spaceone/inventory_v2/model/collector/request.py
  src/spaceone/inventory_v2/service/collector_service.py
Labels: bug

#9 Add job interface and api
  src/spaceone/inventory_v2/interface/grpc/__init__.py
  src/spaceone/inventory_v2/interface/grpc/job.py
  src/spaceone/inventory_v2/model/collector/request.py
  src/spaceone/inventory_v2/model/job/request.py
  src/spaceone/inventory_v2/model/job/response.py
  src/spaceone/inventory_v2/service/job_service.py
Labels: enhancement

#10 fix: fix request field type error at collector get request
  src/spaceone/inventory_v2/model/collector/request.py
Labels: bug

#11 Add job task service
  src/spaceone/inventory_v2/interface/grpc/__init__.py
  src/spaceone/inventory_v2/interface/grpc/job_task.py
  src/spaceone/inventory_v2/manager/job_task_detail_manager.py
  src/spaceone/inventory_v2/manager/job_task_manager.py
  src/spaceone/inventory_v2/model/__init__.py
  src/spaceone/inventory_v2/model/collector/request.py
  src/spaceone/inventory_v2/model/job_task/database.py
  src/spaceone/inventory_v2/model/job_task/request.py
  src/spaceone/inventory_v2/model/job_task/response.py
  src/spaceone/inventory_v2/service/collector_service.py
  src/spaceone/inventory_v2/service/job_task_service.py
Labels: enhancement

#14 Add metric service create api
  src/spaceone/inventory_v2/connector/collector_plugin_connector/collector_plugin_v1_connector.py
  src/spaceone/inventory_v2/error/collect_data.py
  src/spaceone/inventory_v2/interface/grpc/__init__.py
  src/spaceone/inventory_v2/lib/rule_matcher.py
  src/spaceone/inventory_v2/manager/asset_manager.py
  src/spaceone/inventory_v2/manager/asset_type_manager.py
  src/spaceone/inventory_v2/manager/collecting_manager.py
  src/spaceone/inventory_v2/manager/collector_rule_manager.py
  src/spaceone/inventory_v2/manager/identity_manager.py
  src/spaceone/inventory_v2/manager/metric_manager.py
  src/spaceone/inventory_v2/model/asset/database.py
  src/spaceone/inventory_v2/model/asset/request.py
  src/spaceone/inventory_v2/model/asset/response.py
  src/spaceone/inventory_v2/model/asset_type/database.py
  src/spaceone/inventory_v2/model/metric/request.py
  src/spaceone/inventory_v2/service/asset_service.py
  src/spaceone/inventory_v2/service/asset_type_service.py
  src/spaceone/inventory_v2/service/collector_service.py
  src/spaceone/inventory_v2/service/metric_service.py
Labels: enhancement, fail/signedoff

#15 Add metric data service
  src/spaceone/inventory_v2/interface/grpc/__init__.py
  src/spaceone/inventory_v2/interface/grpc/metric_data.py
  src/spaceone/inventory_v2/interface/grpc/metric_example.py
  src/spaceone/inventory_v2/managed_resource/metric/created_count.yaml
  src/spaceone/inventory_v2/managed_resource/metric/total_count.yaml
  src/spaceone/inventory_v2/manager/metric_example_manager.py
  src/spaceone/inventory_v2/model/metric/request.py
Labels: enhancement

#16 Add class variable at region manager for using ResourceManager feat: add history api for Asset
  src/spaceone/inventory_v2/connector/collector_plugin_connector/collector_plugin_v1_connector.py
  src/spaceone/inventory_v2/interface/grpc/__init__.py
  src/spaceone/inventory_v2/interface/grpc/asset.py
  src/spaceone/inventory_v2/manager/__init__.py
  src/spaceone/inventory_v2/manager/asset_manager.py
  src/spaceone/inventory_v2/manager/collecting_manager.py
  src/spaceone/inventory_v2/manager/history_manager.py
  src/spaceone/inventory_v2/manager/region_manager.py
  src/spaceone/inventory_v2/model/__init__.py
  src/spaceone/inventory_v2/model/asset/database.py
  src/spaceone/inventory_v2/model/asset/request.py
  src/spaceone/inventory_v2/model/asset/response.py
  src/spaceone/inventory_v2/service/asset_service.py
Labels: enhancement

#17 fix: Fix changed namespacegroup_id, namespace_id param check
  src/spaceone/inventory_v2/interface/grpc/__init__.py
  src/spaceone/inventory_v2/manager/namespace_group_manager.py
  src/spaceone/inventory_v2/manager/namespace_manager.py
  src/spaceone/inventory_v2/model/namespace_group/request.py
  src/spaceone/inventory_v2/service/namespace_group_service.py
  src/spaceone/inventory_v2/service/namespace_service.py
Labels: bug, enhancement, fail/signedoff

#19 fix: Update metric_id type to enforce string requirement in MetricExa…
  src/spaceone/inventory_v2/managed_resource/namespace/asset_change_history.yaml
  src/spaceone/inventory_v2/managed_resource/namespace/asset_summary.yaml
  src/spaceone/inventory_v2/managed_resource/namespace/iam_summary.yaml
  src/spaceone/inventory_v2/managed_resource/namespace_group/aws.yaml
  src/spaceone/inventory_v2/managed_resource/namespace_group/azure.yaml
  src/spaceone/inventory_v2/managed_resource/namespace_group/common.yaml
  src/spaceone/inventory_v2/managed_resource/namespace_group/etc.yaml
  src/spaceone/inventory_v2/managed_resource/namespace_group/google_cloud.yaml
  src/spaceone/inventory_v2/manager/managed_resource_manager.py
  src/spaceone/inventory_v2/manager/namespace_group_manager.py
  src/spaceone/inventory_v2/manager/namespace_manager.py
  src/spaceone/inventory_v2/model/metric_example/request.py
  src/spaceone/inventory_v2/model/namespace/database.py
  src/spaceone/inventory_v2/model/namespace_group/database.py
  src/spaceone/inventory_v2/service/namespace_group_service.py
  src/spaceone/inventory_v2/service/namespace_service.py
Labels: enhancement, pass/signedoff
